### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by Cloudwhile** [RandomEnch/nonebot_plugin_makemidi#4]
![image](https://user-images.githubusercontent.com/86512509/193765535-2e5e3d78-e326-4bbf-852d-c816d58ba1dd.png)

**Comment by RandomEnch** [comment]
确保正确安装了fluidsynth

**Comment by Cloudwhile** [comment]
这是正确安装并设置环境变量后的报错


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月4日(周二) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RandomEnch/nonebot_plugin_makemidi] 参数错误 (Issue #4)




 
确保正确安装了fluidsynth
 
&mdash;

**Comment by RandomEnch** [comment]
试着查看插件resources文件夹内有无gm.sf2文件和midi文件夹，并检查midi文件夹内是否成功生成了mid以及对应的wav文件

**Comment by Cloudwhile** [comment]
只生成了midi和sf2文件

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月4日(周二) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RandomEnch/nonebot_plugin_makemidi] 参数错误 (Issue #4)

**Comment by RandomEnch** [comment]
mid转换wav过程用到了gm.sf文件2和fluidsynth的相关代码，确保正确设置了fluidsynth环境变量。简单的验证方式：在cmd中输入fluidsynth能弹出相应信息而不是"不是内部或外部命令，也不是可运行的程序"。如果仍然不行，尝试重启。

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193776282-00f709b3-2a33-4e80-b00d-7271f7881896.png)

**Comment by RandomEnch** [comment]
可能是Nonebot当前环境未识别到该路径导致的，尝试重启Nonebot或者服务器

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193781337-8d1aa9f2-0e6e-48ce-a3a4-bbc8bb12908d.png)
不行

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193781496-7bc8077e-5c72-4b8f-af69-30e4ff2cdc4d.png)
rr仍然不行

**Comment by RandomEnch** [comment]
wav文件是否正常生成了？安装ffmpeg应该可以解决该问题

**Comment by Cloudwhile** [comment]
10-04 17:20:35 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_makemidi) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_makemidi\__init__.py", line 44, in _
    await make_music.finish(result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 473, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 458, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 116, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='1', msg='SEND_MSG_API_ERROR', retcode

ffmpeg 已安装
.wav生成但仍不行
![image](https://user-images.githubusercontent.com/86512509/193784144-41478072-d310-4725-b132-6ed7709a9a40.png)

**Comment by RandomEnch** [comment]
如果正常生成了wav文件，插件就是正常运行了。无法发送wav文件是因为未安装ffmpeg。

**Comment by Cloudwhile** [comment]
可你看到了底部最后一张图

**Comment by RandomEnch** [comment]
ffmpeg的安装方式和fluidsynth一样是添加path，而不是用pip。下载地址可在go-cqhttp官方文档找到。https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg

**Comment by chilldenpa** [comment]
我文件夹里已经有mid文件了但是
编曲失败，参数错误：[WinError 2] 系统找不到指定的文件。

**Comment by RandomEnch** [comment]
> 我文件夹里已经有mid文件了但是 编曲失败，参数错误：[WinError 2] 系统找不到指定的文件。

确保正确安装fluidsynth并设置环境变量

**Comment by chilldenpa** [comment]
![6OAKYCM9S~@C2@PQ(15`2I7](https://user-images.githubusercontent.com/116000272/196327401-b687d842-29b5-4f6f-b1bd-1e431634e7fa.png)
![GSFDS{ $Q AOF757@4C @I9](https://user-images.githubusercontent.com/116000272/196327471-f6e63523-c44e-4b6e-9016-9e3015def42b.png)

**Comment by RandomEnch** [comment]
参考上述方法，先尝试重启nonebot并检查mid文件夹内是否正确生成对应文件

**Comment by chilldenpa** [comment]
![E$4A 9FQPN{BMX523HIRXG6](https://user-images.githubusercontent.com/116000272/196399040-b16303db-439e-4eb4-bf3b-7a11ffe4d7fe.png)
还是不行，请问这个文件是什么

**Comment by chilldenpa** [comment]
这样应该设置好了吧
![Uploading })Z5K0X~ZZACID[J4~8@{8V.png…]()

**Comment by chilldenpa** [comment]
![})Z5K0X~ZZACID J4~8@{8V](https://user-images.githubusercontent.com/116000272/196402116-a8be874c-1ca0-41ae-8898-c045502585b8.png)
这样算设置好了吗

**Comment by chilldenpa** [comment]
![8KGILG3X39SE4Q 3PR0SHZY](https://user-images.githubusercontent.com/116000272/196402385-a74a3d7e-a3f5-4d70-8a8a-c33e303d612d.png)
调试出错

**Comment by RandomEnch** [comment]
如果不会加载插件或者部署的话，请熟读官方提供的使用文档

**Comment by chilldenpa** [comment]
ok了，谢谢
注意文件名要小写
![image](https://user-images.githubusercontent.com/116000272/196419381-f2e769d1-f131-48b3-8861-255ec7dddf1f.png)
